[build]
builder = "heroku/buildpacks:20"

[variables]
NODE_VERSION = "22.12.0"

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "corepack enable",
  "yarn install --frozen-lockfile"
]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "yarn dev"
