[variables]
NODE_VERSION = "22.12.0"

[phases.setup]
# Optional: Confirm Node version used during build
cmds = ["node -v"]

[phases.install]
cmds = [
  "corepack enable",
  "yarn install --frozen-lockfile"
]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "yarn dev"
