[variables]
NODE_VERSION = "22.12.0"

[phases.setup]
cmds = [
  "echo 🚀 Using Node version: $(node -v)"
]

[phases.install]
cmds = [
  "corepack enable",
  "yarn install --frozen-lockfile"
]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "yarn dev"